# Generated by Django 4.0.3 on 2023-03-08 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0004_automobilevo_is_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobilevo',
            name='is_sold',
            field=models.BooleanField(null=True),
        ),
    ]
