# Generated by Django 4.0.3 on 2023-03-16 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0005_alter_automobilevo_is_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='automobilevo',
            name='picture_url',
            field=models.URLField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='automobilevo',
            name='is_sold',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
