# Generated by Django 4.0.3 on 2023-03-08 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0005_alter_appointment_vip_alter_appointment_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='color',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='model',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='year',
        ),
    ]
