# Generated by Django 4.0.3 on 2023-03-09 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0006_remove_appointment_color_remove_appointment_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technician',
            name='employee_number',
            field=models.PositiveSmallIntegerField(unique=True),
        ),
    ]
